services:
  - type: web
    name: vaquita
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromGroup: vaquita-secrets
      - key: Security__EncryptionKey
        fromGroup: vaquita-secrets
